{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework",
    "module": "spring-test",
    "version": "6.1.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.springframework",
          "module": "spring-core",
          "version": {
            "requires": "6.1.1"
          }
        }
      ],
      "files": [
        {
          "name": "spring-test-6.1.1.jar",
          "url": "spring-test-6.1.1.jar",
          "size": 852359,
          "sha512": "193a90c1dfb4fd75697450bab0efa37b3073bb519f32a895c1356e77096d55d54f278a46a6d3fb40a7f1b9d420b8bda95293f3f8b10d990371d5642532cbe2a0",
          "sha256": "bed1628a721a5b00c0dae73835b3049b0812439cfc789251db699c9c62059e62",
          "sha1": "0e86044a9b56e7c6860d643dd11b7b44624cce4a",
          "md5": "c827e75b9a156221b09739f66de43d9c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.springframework",
          "module": "spring-core",
          "version": {
            "requires": "6.1.1"
          }
        }
      ],
      "files": [
        {
          "name": "spring-test-6.1.1.jar",
          "url": "spring-test-6.1.1.jar",
          "size": 852359,
          "sha512": "193a90c1dfb4fd75697450bab0efa37b3073bb519f32a895c1356e77096d55d54f278a46a6d3fb40a7f1b9d420b8bda95293f3f8b10d990371d5642532cbe2a0",
          "sha256": "bed1628a721a5b00c0dae73835b3049b0812439cfc789251db699c9c62059e62",
          "sha1": "0e86044a9b56e7c6860d643dd11b7b44624cce4a",
          "md5": "c827e75b9a156221b09739f66de43d9c"
        }
      ]
    }
  ]
}
